### ISSUE TITLE
Error while running the application - Poco::Net::ConnectionRefusedException

### ISSUE THREAD

**Issue by vasavi158** [cortexica/intel-rrk-safety#1]
Hi,
I have followed the steps mentioned in ReadMe File and generated bin/sample executable. But while running the sample application I am facing the following Error 
------------ERROR-------------------
terminate called after throwing an instance of 'Poco::Net::ConnectionRefusedException'
  what():  Connection refused
Aborted (core dumped)
------------ERROR-------------------
Can you help me solving the issue.

**Comment by mpeniak** [comment]
Hi,

I was not expecting anyone would be trying this just yet as the RRK has not yet been released for sale.
Could you please confirm what are you trying to do? The sample you mention requires a service that would only run on the purchased RRK and that service is close-source so you should not have it. That is the issue I think.

Thanks
